version: "3"

services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
  
  app: 
    container_name: susau
    build: .
    volumes:
      - redis-data:/data
    ports:
      - "6069:6069"
    networks:
      - redis-net
    depends_on:
      - redis
      
   
networks:
  redis-net:

volumes:
  redis-data: